version: "3.9"
services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./ChatApp:/ChatApp
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=chatdb
      - DB_USER=chatuser
      - DB_PASS=pass123
    depends_on:
      - db
    restart: always

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=chatdb
      - POSTGRES_USER=chatuser
      - POSTGRES_PASSWORD=pass123
    restart: always

volumes:
  dev-db-data: